spring.application.name=loyalty-club
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/loyalty_db}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog-master.xml
spring.liquibase.drop-first=false

server.port=8089

security.jwt.secret=${JWT_SECRET:YWRtaW5Mb3lhbHR5Q2x1YlNlY3JldEtleUFkbWluTG95YWx0eUNsdWJTZWNyZXRLZXk=}
security.jwt.expiration-ms=900000
app.available-country-codes=PL,DE,CZ,SK,LT
app.store.default-points-per-currency=1.00
spring.threads.virtual.enabled=true
